"""Add GainLoss column to CallBook table

Revision ID: 0dd5b47efb7f
Revises: 2f32d632b209
Create Date: 2024-02-22 12:16:56.988497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd5b47efb7f'
down_revision = '2f32d632b209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_book')
    op.drop_table('_alembic_tmp_call_book')
    with op.batch_alter_table('CallBook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('GainLoss', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CallBook', schema=None) as batch_op:
        batch_op.drop_column('GainLoss')

    op.create_table('_alembic_tmp_call_book',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('TimeStamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('AnalystName', sa.VARCHAR(length=50), nullable=False),
    sa.Column('Date', sa.DATE(), nullable=False),
    sa.Column('ScripName', sa.VARCHAR(length=50), nullable=False),
    sa.Column('Position', sa.VARCHAR(length=10), nullable=False),
    sa.Column('EntryPrice', sa.FLOAT(), nullable=False),
    sa.Column('Target1', sa.FLOAT(), nullable=False),
    sa.Column('Target2', sa.FLOAT(), nullable=False),
    sa.Column('StopLoss', sa.FLOAT(), nullable=False),
    sa.Column('Remark', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('Status', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_book',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('TimeStamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('AnalystName', sa.VARCHAR(length=50), nullable=False),
    sa.Column('Date', sa.DATE(), nullable=False),
    sa.Column('ScripName', sa.VARCHAR(length=50), nullable=False),
    sa.Column('Position', sa.VARCHAR(length=10), nullable=False),
    sa.Column('EntryPrice', sa.FLOAT(), nullable=False),
    sa.Column('Target1', sa.FLOAT(), nullable=False),
    sa.Column('Target2', sa.FLOAT(), nullable=False),
    sa.Column('StopLoss', sa.FLOAT(), nullable=False),
    sa.Column('Success', sa.BOOLEAN(), nullable=True),
    sa.Column('GainLoss', sa.FLOAT(), nullable=True),
    sa.Column('Remark', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
