"""initial migration

Revision ID: 2029919c017c
Revises: 
Create Date: 2024-01-18 20:24:12.429121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2029919c017c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.alter_column('Success',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('GainLoss',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.alter_column('GainLoss',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('Success',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
