"""Description of changes

Revision ID: cb9431271ddc
Revises: 0dd5b47efb7f
Create Date: 2024-03-03 00:04:03.437161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9431271ddc'
down_revision = '0dd5b47efb7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accesstoken', sa.String(length=1000), nullable=False),
    sa.Column('TimeStamp', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accesstoken')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_token')
    # ### end Alembic commands ###
